switch to SQL for freq count
order by count(*) desc

in

val byFreq = sqlContext.sql(   """     select geohash,count(*)     from tweets     group by geohash     order by count(*) desc   """.stripMargin) 

causes:

java.lang.UnsupportedOperationException: Cannot evaluate expression: count(1)
					 at org.apache.spark.sql.catalyst.expressions.Unevaluable$class.eval(Expression.scala:188)
					 at org.apache.spark.sql.catalyst.expressions.Count.eval(aggregates.scala:156)
					 at org.apache.spark.sql.catalyst.expressions.InterpretedOrdering.compare(ordering.scala:36)
					 at org.apache.spark.sql.catalyst.expressions.InterpretedOrdering.compare(ordering.scala:27)